version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vollmed_api
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db_data: {}

# executar o seguinte comando para entrar no mysql
# mysql -uroot -proot(dentro do container) ou docker exec -it <container_id> mysql -uroot -proot
# para encontrar o nome do container, digite o seguinte comando:
# docker ps -l  --format "table {{.Names}}"